title: Knowledge Graph # your name (or website title) here
logo: "images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
   <br><br>
   We're going to take you on a fun journey to craft a stunning personal website using GitLab Pages! We’ve got a super simple, versatile template that you can easily jazz up to reflect your unique style.   <br><br>
   Graph
   <br><br>
   
theme: jekyll-theme-minimal
future: true
